### PR TITLE
Upstream Merge 4/19

### PR DESCRIPTION
**Pull request by Jolly-66**
i fucking hate this game

DMIs this merge may cause issues in game (errors/CSS textures) since effects.dmi got deleted when i was doing this
all the code should be fine, i wanna say somethign somewhere got replaced (maybe skrell code cause i forget where that was) since i just accepted incoming on almost 200 files

image

### CODE REVIEW

**Comment by Jolly-66** [comment]
lol sqn got tagged cause of map shit oops

**Comment by Jolly-66** [comment]
it compiled on the 19th but not today ok cool

**Review by MrMelbert — APPROVED** [review]
i checked all the non-module comments and didn't see anything get replaced (assuming I didn't miss anything)

**Comment by Jolly-66** [comment]
i squashed dw

**Comment by MrMelbert** [comment]
i was waiting for the checks to pass to see if I fixed it 😔

**Pull request merged**
