### PR TITLE
Beach Episode Master PR (real)

### PR DESCRIPTION
**Pull request by Jolly-66**
RETAKE BECAUSE I OBVIOUSLY KNOW HOW TO USE VSCODE GIT COMMANDS.
Doing this so I have the branch for later, and so the PR exists so others can push to it too.

Things left to do:
- [ ] Clothing + Accessories (sprites required too)
- [ ] Pool systyem

Optional things left to do:
- [ ] Hyperthermia/hypothermia/sunburn
- [ ] Sunscreen system

Entire thing being done by with the help of Melbert, Prodirus for code and Clark/Blueshirtguy on sprites.

### CODE REVIEW

**Comment by prodirus** [comment]
LITERALLY NOTHING

**Comment by Jolly-66** [comment]
did i ask for your opinion

**Comment by prodirus** [comment]
> did i ask for your opinion
a pull request is a request for discussion and review, if you didn't want anyone's opinion we'd be working off a branch or you'd merge it straight into master 😺

**Comment by Jolly-66** [comment]
> > did i ask for your opinion
> 
> a pull request is a request for discussion and review, if you didn't want anyone's opinion we'd be working off a branch or you'd merge it straight into master 😺

im gonna hide this like oranges does to bad comments

**Comment by Jolly-66** [comment]
should've done that when i made this

**Comment by Jolly-66** [comment]
prepping for new repo + melbert suggested moving this to a branch, which we'll do

**Pull request closed without merging**
