### PR TITLE
The Great Lima-ning: Lima 3(?) (Or something like that) (Remastered)

### LINKED ISSUE #90: Lima Atmos Remap
Marking this as a feature since it isn't a bug, but if someone could get on it or whenever SQN has the time to remap her bean station.

### PR DESCRIPTION
**Pull request by MrMelbert**
Many many many hours of blood, sweat, tears, and a file corruption that deleted a day of work has lead to Lima: Functioning & Up-to-date (for now?)

closes #90

- **The entire station was re-piped.**
- **The entire camera net was redone.**
- All the departments now have cargobus consoles.
- There is now a drone bay.
image
- There is now a cryogenics room.
image
- Medbay, Dorms, the Kitchen, Permabrig, and a few other areas are now plumbed.
image
- A shit ton of wall mounted items were converted to directionals and a shit ton of wall mounted items were added (newscasters, intercoms, entertainment monitors, etc etc)
- A ton of holo-pads were installed.
- A large amount of maintenance loot was added or revamped.
- Cargo bay received a small expansion for a mech bay.
image
- Meteor shields were added around a few places, and telecomms recieved some slight adjustments.
- **A large amount of engineering was remapped.**
- Atmos's office was enlarged slightly.
image
- The SMESs now no longer need multilayer cable terminals, as the SM cabling was redone.
- The lower part of engineering was turned into an equipment room.
image
- The central part of engineering was redone with new tiles. 
- The gravity generator was moved to where tech storage was.
image
- ...And Tech Storage was moved to where the gravity generator was, giving it a ""public"" access door.
image
- Made the solar panels actual use their proper area instead of maintenance area.
- Made the bridge use a real actual area instead of the abstract 'command' area.
- Made Ian's Room use the corporate showroom area.
- Permabrig's area's were redone with the new work / rec / etc area.
- Overall, more places use the new textured and alternative floor tiling. 
- Spawn locations for a few modular jobs were added. 
- ...And probably more I missed?

### CODE REVIEW

**Review by Jolly-66 — APPROVED** [review]
Seems fine by me.
Double check to make sure nothing breaks and what not. If SQN is alright then you have permission to merge this, either one of you

Also make sure to close the one issue that's labeled for this ty

**Comment by Jolly-66** [comment]
#90 
Idk how to make things mark as auto close but this is it

**Comment by MrMelbert** [comment]
sqn reviewed it, from what i've seen in game nothing breaks, no runtimes

**Comment by Jolly-66** [comment]
> sqn reviewed it, from what i've seen in game nothing breaks, no runtimes

Squash and merge then if its all good

**Pull request merged**
